/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-06-08 02:15:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ticket;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailTicket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://service.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_payment() {\r\n");
      out.write("    /*  location.href = \"payment.jsp\"; */\r\n");
      out.write("    \r\n");
      out.write(" var IMP = window.IMP; // 생략가능\r\n");
      out.write(" \r\n");
      out.write(" IMP.init('iamport'); // 'iamport' 대신 부여받은 \"가맹점 식별코드\"를 사용\r\n");
      out.write(" \r\n");
      out.write(" IMP.request_pay({\r\n");
      out.write("      pg : 'inicis', // version 1.1.0부터 지원.\r\n");
      out.write("      pay_method : 'card',\r\n");
      out.write("      merchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("      name : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("      amount : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_fixedprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("      buyer_email : 'iamport@siot.do',\r\n");
      out.write("      buyer_name : '구매자이름',\r\n");
      out.write("      buyer_tel : '010-1234-5678',\r\n");
      out.write("      buyer_addr : '서울특별시 금천구',\r\n");
      out.write("      buyer_postcode : '123-456',\r\n");
      out.write("      m_redirect_url : 'https://www.yourdomain.com/payments/complete'\r\n");
      out.write("  }, function(rsp) {\r\n");
      out.write("      if ( rsp.success ) {\r\n");
      out.write("          var msg = '결제가 완료되었습니다.';\r\n");
      out.write("          msg += '고유ID : ' + rsp.imp_uid;\r\n");
      out.write("          msg += '상점 거래ID : ' + rsp.merchant_uid;\r\n");
      out.write("          msg += '결제 금액 : ' + rsp.paid_amount;\r\n");
      out.write("          msg += '카드 승인번호 : ' + rsp.apply_num;\r\n");
      out.write("      } else {\r\n");
      out.write("          var msg = '결제에 실패하였습니다.';\r\n");
      out.write("          msg += '에러내용 : ' + rsp.error_msg;\r\n");
      out.write("      }\r\n");
      out.write("      alert(msg);\r\n");
      out.write("  });\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"banner\" class=\"product\">\r\n");
      out.write("\t\t<div class=\"i_wrap background\">\r\n");
      out.write("\t\t\t<i class=\"image\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%; height: 100%; background-image: url('http://c2.poing.co.kr/MRI-original/MjAxODAz/15217123715ab37cf3d5f10.jpeg')\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"i_wrap blur background\">\r\n");
      out.write("\t\t\t<i class=\"image\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%; height: 100%; background-image: url('http://c2.poing.co.kr/MRI-original/MjAxODAz/15217123715ab37cf3d5f10.jpeg')\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"inner_wrap\">\r\n");
      out.write("\t\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t\t<span class=\"name\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.s_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.s_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"info\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"body\">\r\n");
      out.write("\t\t\t\t\t<!-- 상점 사진 슬라이드 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"slider_wrap PoingSlider_wrap\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"slider\" class=\"PoingSlider\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"i_wrap slice\" style=\"top: 0px; left: -100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"image\" data-index=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(http://c2.poing.co.kr/MRI-original/MjAxODAz/15217123715ab37cf3d5f10.jpeg)\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"i_wrap slice\" style=\"top: 0px; left: -100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"image\" data-index=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-image: url(http://c2.poing.co.kr/MRI-original/MjAxODAz/15217123725ab37cf448856.jpeg)\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"i_wrap \">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"main\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_discount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" %</span><br> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"sub\"> OFF</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"reduced\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_fixedprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 원</span><br> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"original\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ticket.t_cost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 원</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"content_wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"sidebar_wrap\" class=\"detail\">\r\n");
      out.write("\t\t\t<button class=\"sidebar buy border_radius soft\" data-id=\"2552\"\r\n");
      out.write("\t\t\t\tdata-cart=\"true\" tabindex=\"-1\" onclick=\"fn_payment();\">바로\r\n");
      out.write("\t\t\t\t구매하기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
