/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-06-11 02:16:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/finalproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/koing/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1516843247248L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("#modDiv {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tbackground-color: gray;\t\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\tmargin-top: -50px;\r\n");
      out.write("\tmargin-left: -150px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tz-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".star_rating {\r\n");
      out.write("\tfont-size: 0;\r\n");
      out.write("\tletter-spacing: -4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".star_rating li {\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tletter-spacing: 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tcolor: #ccc;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".star_rating li.on {\r\n");
      out.write("\tcolor: yellow;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-md-1{\r\n");
      out.write("color: #ffffff;\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr.commentLi{\r\n");
      out.write("text-align: center;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h2>댓글등록</h2>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t<table class=\"table\" style=\"background: #b91b39; width: 100%\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 10%;\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 30%;\">댓글내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 20%;\">평점</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 20%;\">첨부파일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 20%;\">예약번호</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"color: #ffffff; font-weight: 1000;text-align: center;\"><input type=\"hidden\" name=\"s_no\" id=\"s_no\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.s_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input type=\"hidden\" name=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"newReplyWriter\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionMember.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionMember.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><textarea name='c_contents' class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid='newReplyText' rows=\"3\" cols=\"40\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"hidden\" name=\"c_score\" id=\"newReplyScore\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"star_rating\" style=\"width: 80%; margin-left: 10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li data-score=\"1\" class=\"on\" style=\"width: 20%;\">★</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li data-score=\"2\" class=\"on\" style=\"width: 20%;\">★</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li data-score=\"3\" class=\"on\" style=\"width: 20%;\">★</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li data-score=\"4\" style=\"width: 20%;\">★</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li data-score=\"5\" style=\"width: 20%;\">★</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"file\" name=\"c_img\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"newReplyImg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><!-- <input type='text' name='r_no' class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid='newReplyTr'> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name='r_no' class=\"form-control\" id='newReplyTr' style=\"height: 50%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">예약날짜선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn\" id=\"replyAddBtn\" style=\"width: 20%; margin-left: 80%\">ADD REPLY</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\" style=\"padding-left: 0; padding-right: 0\">\r\n");
      out.write("\t\t<table class=\"table\" style=\"background: #b91b39; width: 100%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 10%;\">글번호</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 25%;\">등록날짜</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 10%;\">작성자</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 40%;\">내용</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 5%;\">별점</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"col-md-1\" style=\"width: 10%;\">사진</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody id=\"comment\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<ul class='pagination'>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".star_rating li\").on(\"click\", function() {\r\n");
      out.write("\t\t\tvar star = $(this).data(\"score\");\r\n");
      out.write("\t\t\t$(\"#newReplyScore\").val(star);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".star_rating li\").on(\"mouseover\", function() {\r\n");
      out.write("\t\t\t$(this).parent().children(\"li\").removeClass(\"on\");\r\n");
      out.write("\t\t\t$(this).addClass(\"on\").prevAll(\"li\").addClass(\"on\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getPageList(page) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$\r\n");
      out.write("\t\t\t\t\t.getJSON(\r\n");
      out.write("\t\t\t\t\t\t\t\"/comment/\" + s_no + \"/\" + page,\r\n");
      out.write("\t\t\t\t\t\t\tfunction(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(data.list.length);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar str = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(data.list)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<tr data-c_no='\"+this.c_no+\"' class='commentLi'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><div class='c_date'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this.c_no\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><div class='c_date'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this.dateToString\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><div class='id'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this.id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t/* + \"<td><div class='s_no'>\"+this.s_no+\"</div></td>\" */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><div class='c_contents'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this.c_contents\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><div class='c_score'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this.c_score\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><div class='c_img'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ this.c_img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</div></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t/* + \"<td><div class='r_no'>\"+this.r_no+\"</div></td>\" */;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionMember.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == this.id) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><button class='update btn btn-primary'>수정</button></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstr += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#comment\").html(str);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".commentLi\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$(this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\".update\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"click\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_no = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.data(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"c_no\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar idVal = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prevAll(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"td\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".id\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_contentsVal = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prevAll(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"td\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".c_contents\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_scoreVal = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prevAll(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"td\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".c_score\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_imgVal = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prevAll(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"td\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".c_img\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar r_noVal = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthis)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.parent()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prevAll(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"td\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".r_no\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal .modal-body .modal-reply\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.attr(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'data-c_no',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tc_no);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal .modal-body\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyWriter\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tidVal);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal .modal-body\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyText\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tc_contentsVal);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal .modal-body\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyScore\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tc_scoreVal);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//$(\"#replyModifyModal .modal-body\").find(\"#newReplyImg\").val(c_imgVal[1]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal .modal-body\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyTr\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tr_noVal);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//$(\"#replyModifyModal .modal-body\").text($(this).parent(\".s_no\").val());\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.modal(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'show');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#replyModBtn\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"click\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_no = $(\".modal-reply\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.data(\"c_no\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_contents = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".modal-reply\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyText\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_score = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".modal-reply\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyScore\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_img = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\".modal-reply\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#newReplyImg\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'put',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : '/comment/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ c_no,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theaders : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Content-Type\" : \"application/json\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"X-HTTP-Method-Override\" : \"PUT\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata : JSON\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.stringify({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tc_contents : c_contents,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tc_score : c_score,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tc_img : c_img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(\"result: \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (result == 'SUCCESS') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.modal(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"hide\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//getAllList();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tgetPageList(replyPage);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#replyDelBtn\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"click\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar c_no = $(\".modal-reply\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.data(\"c_no\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tconsole.log(\"c_no:\" + c_no);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'delete',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : '/comment/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ c_no,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theaders : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Content-Type\" : \"application/json\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"X-HTTP-Method-Override\" : \"DELETE\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tresult) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(\"result : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ result);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (result == 'SUCCESS') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"삭제 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#replyModifyModal\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.modal(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"hide\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tgetPageList(replyPage);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tprintPaging(data.pageMaker);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar s_no = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${store.s_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t\tgetPageList(1);\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getAllList() {\r\n");
      out.write("\t\t\t$.getJSON(\"/comment/all/\" + s_no, function(data) {\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\tconsole.log(data.length);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(data).each(function() {\r\n");
      out.write("\t\t\t\t\t/* \t\t\tstr += \"<li data-c_no='\"+this.c_no+\"' class='commentLi'  style='border:1px solid #000; width:200px;'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"s_no : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ this.s_no\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"c_contents : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ this.c_contentsq\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"c_score : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ this.c_score\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"<br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"c_img : \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ this.c_img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"</li>\"; */\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#comment\").html(str);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#replyAddBtn\").on(\"click\", function() {\r\n");
      out.write("\t\t\tvar id = $(\"#newReplyWriter\").val();\r\n");
      out.write("\t\t\tvar c_contents = $(\"#newReplyText\").val();\r\n");
      out.write("\t\t\tvar c_score = $(\"#newReplyScore\").val();\r\n");
      out.write("\t\t\tvar c_img = $(\"#newReplyImg\").val();\r\n");
      out.write("\t\t\tvar r_no = $(\"#newReplyTr\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\turl : '/comment/add',\r\n");
      out.write("\t\t\t\theaders : {\r\n");
      out.write("\t\t\t\t\t\"Content-Type\" : \"application/json\",\r\n");
      out.write("\t\t\t\t\t\"X-HTTP-Method-Override\" : \"POST\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tdata : JSON.stringify({\r\n");
      out.write("\t\t\t\t\ts_no : s_no,\r\n");
      out.write("\t\t\t\t\tid : id,\r\n");
      out.write("\t\t\t\t\tc_contents : c_contents,\r\n");
      out.write("\t\t\t\t\tc_score : c_score,\r\n");
      out.write("\t\t\t\t\tc_img : c_img,\r\n");
      out.write("\t\t\t\t\tr_no : r_no\r\n");
      out.write("\t\t\t\t}),\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (result == 'SUCCESS') {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\talert(\"등록 되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\tgetPageList(1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t$(\"#comment\").on(\"click\", \"#update\", function() {\r\n");
      out.write("\t\t// \t\t\tvar c_no = $(this).prev().find(\"data-c_no\").val();\r\n");
      out.write("\t\t// \t\t\talert($(this).text());\r\n");
      out.write("\t\t// \t\t\t\tconsole.log(\"c_no :\" + c_no);\r\n");
      out.write("\t\t// \t\t\t$.getJSON(\"/comment/\"+c_no,function(data){\r\n");
      out.write("\t\t// \t\t\t\tvar str =\"\";\r\n");
      out.write("\t\t// \t\t\t\tvar selected = \"selected\";\r\n");
      out.write("\t\t// \t\t\t\tvar comment = $(this).prev();\r\n");
      out.write("\t\t// \t\t\t\t$(data).each(function(index, e){\r\n");
      out.write("\t\t// \t\t\t\t\t/* alert(\"aaa\",$(this).find(\"li\").text()); */\t\r\n");
      out.write("\t\t// \t\t\t\t\tif(this.c_no == comment.attr(\"data-c_no\")){\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t\t\t\tstr += \"<li data-c_no='\"+this.c_no+\"' class='commentLi'  style='border:1px solid #000; width:300px;'>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"c_contents : \"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"<input type='text' name='c_contents' id='newReplyText' value='\"+this.c_contents+\"'>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"<br>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"c_score : \"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"<select name='c_score' id='newReplyScore' style='color:#920021;'\";\r\n");
      out.write("\t\t// \t\t\t\t\tfor(var i = 0; i<6; i++){\r\n");
      out.write("\t\t// \t\t\t\t\t\tif(this.c_score == i){\r\n");
      out.write("\t\t// \t\t\t\t\t\t\tstr += \"<option value='\"+i+\"' \"+selected+\">\"+i+\"</option>\";\r\n");
      out.write("\t\t// \t\t\t\t\t\t} else{\r\n");
      out.write("\t\t// \t\t\t\t\t\t\tstr += \"<option value='\"+i+\"'>\"+i+\"</option>\";\r\n");
      out.write("\t\t// \t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t\t\t\t}\r\n");
      out.write("\t\t// \t\t\t\t\tstr += \"</select>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"<br>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"c_score : \"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"<input type='text' name='c_img' id='newReplyImg' value='\"+this.c_img+\"'>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"</li>\"\r\n");
      out.write("\t\t// \t\t\t\t\t+ \"<button id='replyModBtn'>수정</button>\";\r\n");
      out.write("\t\t// \t\t\t\t\t}else{\r\n");
      out.write("\t\t// \t\t\t\t\t\talert(\"안됨\");\r\n");
      out.write("\t\t// \t\t\t\t\t}\r\n");
      out.write("\t\t// \t\t\t\t});\r\n");
      out.write("\t\t// \t\t\t\tvar text = $(this).prev().val();\r\n");
      out.write("\t\t// \t\t\t\talert(text);\r\n");
      out.write("\t\t// \t\t\t\tvar c_no = comment.attr(\"data-c_no\");\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t\t\t$(\".modal-title\").html(c_no);\r\n");
      out.write("\t\t// \t\t\t\t$(\"#modContent\").html(str);\r\n");
      out.write("\t\t// \t\t\t\t$(\"#modDiv\").show(\"fast\");\r\n");
      out.write("\t\t// \t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t/* var comment = $(this).prev();\r\n");
      out.write("\r\n");
      out.write("\t\tvar c_no = comment.attr(\"data-c_no\");\r\n");
      out.write("\t\tvar c_contents = comment.text();\r\n");
      out.write("\r\n");
      out.write("\t\talert(c_contents);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".modal-title\").html(c_no);\r\n");
      out.write("\t\t$(\"#c_contents\").val(c_contents);\r\n");
      out.write("\t\t$(\"#modDiv\").show(\"fast\"); */\r\n");
      out.write("\t\t// \t\t});\r\n");
      out.write("\t\tfunction printPaging(pageMaker) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar str = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (pageMaker.prev) {\r\n");
      out.write("\t\t\t\tstr += \"<li><a href='\" + (pageMaker.startPage - 1)\r\n");
      out.write("\t\t\t\t\t\t+ \"'> << </a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (var i = pageMaker.startPage, len = pageMaker.endPage; i <= len; i++) {\r\n");
      out.write("\t\t\t\tvar strClass = pageMaker.cri.page == i ? 'class=active' : '';\r\n");
      out.write("\t\t\t\tstr += \"<li \"+strClass+\"><a href='\"+i+\"'>\" + i + \"</a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (pageMaker.next) {\r\n");
      out.write("\t\t\t\tstr += \"<li><a href='\" + (pageMaker.endPage + 1)\r\n");
      out.write("\t\t\t\t\t\t+ \"'> >> </a></li>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('.pagination').html(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar replyPage = 1;\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".pagination\").on(\"click\", \"li a\", function(event) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\treplyPage = $(this).attr(\"href\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tgetPageList(replyPage);\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"replyModifyModal\" tabindex=\"-1\"\r\n");
      out.write("\t\trole=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-reply\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\tID : <input type='text' name='id' id='newReplyWriter' readonly>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t댓글 : <input type='text' name='c_contents' id='newReplyText'>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t평점 : <select name=\"c_score\" id=\"newReplyScore\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: #920021;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">★</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">★★</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">★★★</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">★★★★</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"5\">★★★★★</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t첨부파일 : <input type='file' name='c_img' id='newReplyImg'>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t예약 정보 : <input type='text' name='r_no' id='newReplyTr' readonly>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" id=\"replyDelBtn\">Delete</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"replyModBtn\">Save\r\n");
      out.write("\t\t\t\t\t\tchanges</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Modal End -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/review/comment.jsp(98,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("list");
    // /WEB-INF/views/review/comment.jsp(98,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/review/comment.jsp(98,9) '${reserveList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reserveList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.r_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.r_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.r_time }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
