/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-05-24 07:58:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bootstrap;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\tAuthor: W3layouts\r\n");
      out.write("\tAuthor URL: http://w3layouts.com\r\n");
      out.write("\tLicense: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("\tLicense URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Weblog a Blogging Category Bootstrap responsive WebTemplate | Register :: w3layouts</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"Weblog a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\taddEventListener(\"load\", function () {\r\n");
      out.write("\t\t\tsetTimeout(hideURLbar, 0);\r\n");
      out.write("\t\t}, false);\r\n");
      out.write("\r\n");
      out.write("\t\tfunction hideURLbar() {\r\n");
      out.write("\t\t\twindow.scrollTo(0, 1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<link href=\"/css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<link href=\"/css/single.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<link href=\"/css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("\t<link href=\"/css/fontawesome-all.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800\"\r\n");
      out.write("\t    rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--Header-->\r\n");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div class=\"top-bar_sub_w3layouts container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 logo text-left\">\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"index\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fab fa-linode\"></i> Weblog</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0\">\r\n");
      out.write("\t\t\t\t\t<span>Welcome Back!</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"mx-lg-4 mx-md-2  mx-1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-lock\"></i> Sign In</a>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"register\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"far fa-user\"></i> Register</a>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 log-icons text-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"social_list1 mt-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"facebook1 mx-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"twitter2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fab fa-twitter\"></i>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"dribble3 mx-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fab fa-dribbble\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"pin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fab fa-pinterest-p\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header_top\" id=\"home\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler navbar-toggler-right mx-auto\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"index\">Home\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"about\">About</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t    aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\tFeatures\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"blog1\">Standard Blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"blog2\">2 Column Blog</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"blog3\">3 Column Blog</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"contact\">Contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\" class=\"form-inline my-2 my-lg-0 header-search\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search here...\" name=\"Search\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn1 my-2 my-sm-0\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--//header-->\r\n");
      out.write("\r\n");
      out.write("\t<!--/banner-->\r\n");
      out.write("\t<div class=\"banner-inner\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t<li class=\"breadcrumb-item\">\r\n");
      out.write("\t\t\t<a href=\"index\">Home</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"breadcrumb-item active\">Register</li>\r\n");
      out.write("\t</ol>\r\n");
      out.write("\t<!--//banner-->\r\n");
      out.write("\t<!--/main-->\r\n");
      out.write("\t<section class=\"main-content-w3layouts-agileits\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h3 class=\"tittle\">Register Now</h3>\r\n");
      out.write("\t\t\t\t<div class=\"inner-sec\">\r\n");
      out.write("\t\t\t<div class=\"login p-5 bg-light mx-auto mw-100\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"validationCustom01\">First name</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"validationDefault01\" placeholder=\"\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"validationCustom02\">Last name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"validationDefault02\" placeholder=\"\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputPassword1 mb-2\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password1\" placeholder=\"\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputPassword2 mb-2\">Confirm Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password2\" placeholder=\"\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary submit mb-4\">Register</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">By clicking Signup, I agree to your terms</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--//main-->\r\n");
      out.write("\t<!--footer-->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 footer-grid-agileits-w3ls text-left\">\r\n");
      out.write("\t\t\t\t\t<h3>About US</h3>\r\n");
      out.write("\t\t\t\t\t<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. lacinia eget consectetur sed, convallis at tellus..</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"read\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single\" class=\"btn btn-primary read-m\">Read More</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 footer-grid-agileits-w3ls text-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"tech-btm\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Latest Posts</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-grids row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 blog-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/images/bootstrap/4.jpg\" class=\"img-fluid\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 blog-grid-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single\">Pellentesque dui, non felis. Maecenas male non felis </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"far fa-clock\"></i> 20 Jan, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-grids row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 blog-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/images/bootstrap/5.jpg\" class=\"img-fluid\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 blog-grid-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single\">Pellentesque dui, non felis. Maecenas male non felis </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"far fa-clock\"></i> 20 Jan, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-grids row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-5 blog-grid-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/images/bootstrap/6.jpg\" class=\"img-fluid\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-7 blog-grid-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single\">Pellentesque dui, non felis. Maecenas male non felis </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"sub-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"far fa-clock\"></i> 20 Jan, 2018</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- subscribe -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left\">\r\n");
      out.write("\t\t\t\t\t<h2>Signup to our newsletter</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"subscribe-main text-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"subscribe-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"#\" method=\"post\" class=\"subscribe_form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"email\" placeholder=\"Enter your email...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary submit\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p>We respect your privacy.No spam ever!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- //subscribe -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- footer -->\r\n");
      out.write("\t\t\t<div class=\"footer-cpy text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-social\">\r\n");
      out.write("\t\t\t\t\t<div class=\"copyrighttop\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"mx-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"facebook\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Facebook</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"facebook\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fab fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Twitter</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"mx-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"facebook\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fab fa-google-plus-g\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Google+</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"facebook\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fab fa-pinterest-p\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Pinterest</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"w3layouts-agile-copyrightbottom\">\r\n");
      out.write("\t\t\t\t\t<p>© 2018 Weblog. All Rights Reserved | Design by\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://w3layouts.com/\">W3layouts</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!---->\t\r\n");
      out.write("\t<!-- js -->\r\n");
      out.write("\t<script src=\"/js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("\t<!-- //js -->\r\n");
      out.write("\t<!-- password-script -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\twindow.onload = function () {\r\n");
      out.write("\t\t\tdocument.getElementById(\"password1\").onchange = validatePassword;\r\n");
      out.write("\t\t\tdocument.getElementById(\"password2\").onchange = validatePassword;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction validatePassword() {\r\n");
      out.write("\t\t\tvar pass2 = document.getElementById(\"password2\").value;\r\n");
      out.write("\t\t\tvar pass1 = document.getElementById(\"password1\").value;\r\n");
      out.write("\t\t\tif (pass1 != pass2)\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"password2\").setCustomValidity(\"Passwords Don't Match\");\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"password2\").setCustomValidity('');\r\n");
      out.write("\t\t\t//empty string means no validation error\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //password-script -->\r\n");
      out.write("\r\n");
      out.write("\t<!--/ start-smoth-scrolling -->\r\n");
      out.write("\t<script src=\"/js/move-top.js\"></script>\r\n");
      out.write("\t<script src=\"/js/easing.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tjQuery(document).ready(function ($) {\r\n");
      out.write("\t\t\t$(\".scroll\").click(function (event) {\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\t\tscrollTop: $(this.hash).offset().top\r\n");
      out.write("\t\t\t\t}, 900);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--// end-smoth-scrolling -->\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t\t\t\t \t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t*/\r\n");
      out.write("\r\n");
      out.write("\t\t\t$().UItoTop({\r\n");
      out.write("\t\t\t\teasingType: 'easeOutQuart'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<a href=\"#home\" class=\"scroll\" id=\"toTop\" style=\"display: block;\">\r\n");
      out.write("\t\t<span id=\"toTopHover\" style=\"opacity: 1;\"> </span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- //Custom-JavaScript-File-Links -->\r\n");
      out.write("\t<script src=\"/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
