/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-06-11 00:25:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertStore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/finalproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/koing/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1516843247248L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- jQuery 2.1.4 -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.1.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.1.4.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../vendor/bootstrap/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/flexslider.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/mypage.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".fileDrop {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tborder: 1px dotted gray;\r\n");
      out.write("\tbackground-color: lightslategray;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"br-light\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/ticketmain.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container-diy\" style=\"width: 80%; margin-left: 10%;\">\r\n");
      out.write("\t\t<h2>상점 등록</h2>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<form id=\"insertForm\" role=\"form\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"s_no\" name=\"s_no\" value=\"A07\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionMember.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionMember.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상점 이름</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"s_name\" name=\"s_name\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"상점 이름 입력\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상점 주소</th>\r\n");
      out.write("<!-- \t\t\t\t\t\t<td><input type=\"text\" name=\"s_address\" size=\"40\" -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\tplaceholder=\"주소\"></td> -->\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"s_address\" name=\"s_address\" placeholder=\"주소\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_address2\" name=\"s_address\" placeholder=\"상세주소\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"s_tel\" name=\"s_tel\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"전화번호\"> <!-- <select id=\"s_tel\" name=\"s_tel1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0002\" selected>02</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0031\">031</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0032\">032</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0033\">033</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0041\">041</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0042\">042</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0043\">043</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0051\">051</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0052\">052</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0053\">053</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0054\">054</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0055\">055</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0061\">061</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0062\">062</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0063\">063</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0064\">064</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0502\">0502</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>-\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"s_tel\" name=\"s_tel2\" placeholder=\"\">-\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"s_tel\" name=\"s_tel3\" placeholder=\"\"> -->\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>이미지</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"file\" id=\"s_img\" name=\"s_img\"> ");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"fileDrop\"></div></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>첨부 파일 목록</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"mailbox-attachments clearfix uploadedList\">\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>카테고리</th>\r\n");
      out.write("\t\t\t\t\t\t<td><select id=\"s_category\" name=\"s_category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"한식\">한식</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"양식\">양식</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"일식\">일식</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"중식\">중식</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"아시아식\">아시아식</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>키워드</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"s_keyword\" name=\"s_keyword\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"키워드를 입력하세요\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>상점 소개 글</th>\r\n");
      out.write("\t\t\t\t\t\t<td><textarea rows=\"3\" cols=\"40\" id=\"s_contents\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"s_contents\" placeholder=\"상점 소개 내용\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>지역번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"s_location_no\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"s_location_no\" placeholder=\"지역번호\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-sm pull-right\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-sm pull-right\" style=\"margin-right: 10px;\">등록</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/upload.js\"/>\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script id=\"template\" type=\"text/x-handlebars-template\">\r\n");
      out.write("<li>\r\n");
      out.write("  <span class=\"mailbox-attachment-icon has-img\"><img src=\"{{imgsrc}}\" alt=\"Attachment\"></span>\r\n");
      out.write("  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t<a href=\"{{getLink}}\" class=\"mailbox-attachment-name\">{{fileName}}</a>\r\n");
      out.write("\t<a href=\"{{fullName}}\" \r\n");
      out.write("     class=\"btn btn-default btn-xs pull-right delbtn\"><i class=\"fa fa-fw fa-remove\"></i></a>\r\n");
      out.write("\t</span>\r\n");
      out.write("  </div>\r\n");
      out.write("</li>                \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar template = Handlebars.compile($(\"#template\").html());\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".fileDrop\").on(\"dragenter dragover\", function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".fileDrop\").on(\"drop\", function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar files = event.originalEvent.dataTransfer.files;\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar file = files[0];\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar formData = new FormData();\r\n");
      out.write("\r\n");
      out.write("\t\t\tformData.append(\"file\", file);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '/store/uploadAjax',\r\n");
      out.write("\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\tdataType : 'text',\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar fileInfo = getFileInfo(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar html = template(fileInfo);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\".uploadedList\").append(html);\r\n");
      out.write("\t\t\t\t\t$(\"#s_img\").val(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#insertForm\").submit(\r\n");
      out.write("\t\t\t\tfunction(event) {\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar that = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar str = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\".uploadedList .delbtn\").each(\r\n");
      out.write("\t\t\t\t\t\t\tfunction(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\tstr += \"<input type='hidden' name='files[\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ index + \"]' value='\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ $(this).attr(\"href\") + \"'> \";\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tthat.append(str);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tthat.get(0).submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".uploadedList\").on(\"click\", \".delbtn\", function(event) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar that = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//alert(\"DELETE FILE\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/store/deleteFile\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tfileName : $(this).attr(\"href\")\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"RESULT: \" + result);\r\n");
      out.write("\t\t\t\t\tif (result == 'deleted') {\r\n");
      out.write("\t\t\t\t\t\tthat.closest(\"li\").remove();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://ssl.daumcdn.net/dmaps/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var fullAddr = ''; // 최종 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    fullAddr = data.roadAddress;\r\n");
      out.write("\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    fullAddr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    //법정동명이 있을 경우 추가한다.\r\n");
      out.write("                    if(data.bname !== ''){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있을 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== ''){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\r\n");
      out.write("                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                document.getElementById('s_address').value = fullAddr;\r\n");
      out.write("\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById('sample6_address2').focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
